const LOG_IN = "LOG_IN"
const SET_LOGGED_IN = 'SET_LOGGED_IN'
const REFRESH_ACCESS_TOKEN = 'REFRESH_ACCESS_TOKEN'
const SET_LOG_IN_MESSAGE = 'SET_LOG_IN_MESSAGE'

export default {
    LOG_IN,
    SET_LOGGED_IN,
    REFRESH_ACCESS_TOKEN,
    SET_LOG_IN_MESSAGE
}